//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public string Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string HighestEducation { get; set; }
        public int MarsInPercent { get; set; }
        public string SchoolName { get; set; }
        public string MediumOfEducation { get; set; }
        public string BoardOfEducation { get; set; }
        public string PreferredCourse1 { get; set; }
        public string PreferredCourse2 { get; set; }
        public string preferredCourse { get; set; }
        public string GuardianName { get; set; }
        public string GuardianAddress { get; set; }
        public string GuardianContact { get; set; }
        public System.DateTime DateOfApplication { get; set; }
    }
}
