//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public string CourseId { get; set; }
        public string Degree { get; set; }
        public string Specialization { get; set; }
        public int DurationInYears { get; set; }
        public int Min_APS { get; set; }
        public System.DateTime DateOfAddition { get; set; }
    }
}
